trigger: 
  branches:
    include:
      - master
  paths:
    include:
      - dev    

pool: 
    vmImage: ubuntu-latest

variables:
  workdir: /home/vsts/work/1/s/dev

steps:
- task: TerraformInstaller@0
  displayName: Install Terraform
  inputs:
    terraformVersion: 'v1.5.2'

- checkout: self
  displayName: Checkout Repository   
- task: TerraformCLI@0
  displayName: Terraform Init
  inputs:
    command: 'init'
    workingDirectory: '$(workdir)'
    backendType: 'azurerm'
    backendServiceArm: 'PipelineConnection'
    backendAzureRmSubscriptionId: '87ed7345-6e20-4565-844b-70b8b682de46'
- task: TerraformCLI@0
  displayName: Terraform Validate
  inputs:
    command: 'validate'
    workingDirectory: '$(workdir)'
- task: TerraformCLI@0
  displayName: Terraform Plan
  inputs:
    command: 'plan'
    workingDirectory: '$(workdir)'
    environmentServiceName: 'PipelineConnection'
    providerAzureRmSubscriptionId: '87ed7345-6e20-4565-844b-70b8b682de46'
    publishPlanResults: 'tfplan'

    