trigger: 
  branches:
    include:
      - master
  paths:
    include:
      - dev/*
    exclude:
      - README.md

pool: 
    vmImage: ubuntu-latest

stages:
  - stage: Test
    jobs:
    - job: Install-Terraform
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '1.5.2'

    - job: Checkout-Repository
      steps:
      - checkout: self

    - job: 
      steps:    
      - task: TerraformCLI@0
        displayName: Terraform-Init
        inputs:
          command: 'init'
          workingDirectory: '$(workdir)'
          backendType: 'azurerm'
          backendServiceArm: 'PipelineConnection'
          backendAzureRmSubscriptionId: $(subscription_id)

    - job: Terraform-Validate
      steps:    
      - task: TerraformCLI@0
        inputs:
          command: 'validate'
          workingDirectory: '$(workdir)'

    - job: Terraform-Plan
      steps:    
      - task: TerraformCLI@0
        inputs:
          command: 'plan'
          workingDirectory: '$(workdir)'
          environmentServiceName: 'PipelineConnection'
          providerAzureRmSubscriptionId: $(subscription_id)
          publishPlanResults: 'tfplan'
      
  - stage: Create Release
    jobs:
    - job: Create-Github-Release
      steps:
      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'Github'
          repositoryName: 'c45/bestrong-infra'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'gitTag'
          tagPattern: 'v1.*'
          releaseNotesSource: 'inline'
          changeLogCompareToRelease: 'lastFullRelease'
          changeLogType: 'commitBased'
      