trigger: 
  branches:
    include:
      - master
  paths:
    include:
      - dev    

pool: 
    vmImage: ubuntu-latest


steps:
- task: TerraformInstaller@0
  displayName: Install Terraform
  inputs:
    terraformVersion: 'v1.5.2'

- checkout: self
  displayName: Checkout Repository   
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'PipelineConnection'
    backendAzureRmSubscriptionId: '87ed7345-6e20-4565-844b-70b8b682de46'
- task: TerraformCLI@0
  inputs:
    command: 'validate'
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'PipelineConnection'
    providerAzureRmSubscriptionId: '87ed7345-6e20-4565-844b-70b8b682de46'
    publishPlanResults: 'tfplan'

    