trigger: pr

pool: 
    vmImage: ubuntu-latest

stages:
    - stage: validate
      jobs:
          - job: validate
            continueOnError: false
            steps:
                - task: TerraformInstaller@0
                  displayName: Install
                  inputs:
                    terraformVersion: 'v1.5.2'
                - task: TerraformCLI@0
                  displayName: Terraform Init
                  inputs:
                    command: 'init'
                    backendType: 'azurerm'
                    backendServiceArm: 'PipelineConnection'
                    backendAzureRmSubscriptionId: '87ed7345-6e20-4565-844b-70b8b682de46'
                    backendAzureRmResourceGroupName: 'terraform-state'
                    backendAzureRmStorageAccountName: 'bestrongstatedev'
                    backendAzureRmContainerName: 'tfstate'
                    backendAzureRmKey: 'dev.terraform.tfstate'
                - task: TerraformCLI@0
                  displayName: Terraform Validate
                  inputs:
                    command: 'validate'
                - task: TerraformCLI@0
                  inputs:
                    command: 'plan'
                    environmentServiceName: 'PipelineConnection'
                    providerAzureRmSubscriptionId: '87ed7345-6e20-4565-844b-70b8b682de46'
                    publishPlanResults: 'tfplan'
