trigger: 
  branches:
    include:
      - master
  paths:
    include:
      - dev/*
    exclude:
      - README.md

pool: 
    vmImage: ubuntu-latest

stages:
  - stage: Test
    jobs:
      - job: Test_Terraform_Configuration
        steps:
        - task: TerraformInstaller@0
          displayName: Install Terraform
          inputs:
            terraformVersion: 'v1.5.2'

        - checkout: self
          displayName: Checkout Repository  

        - task: TerraformCLI@0
          displayName: Terraform Init
          inputs:
            command: 'init'
            workingDirectory: '$(workdir)'
            backendType: 'azurerm'
            backendServiceArm: 'PipelineConnection'
            backendAzureRmSubscriptionId: $(subscription_id)

        - task: TerraformCLI@0
          displayName: Terraform Validate
          inputs:
            command: 'validate'
            workingDirectory: '$(workdir)'

        - task: TerraformCLI@0
          displayName: Terraform Plan
          inputs:
            command: 'plan'
            workingDirectory: '$(workdir)'
            environmentServiceName: 'PipelineConnection'
            providerAzureRmSubscriptionId: $(subscription_id)
            publishPlanResults: 'tfplan'

        - task: TerraformCLI@0
          displayName: Terraform Apply
          inputs:
            command: 'apply'
            workingDirectory: '$(workdir)'
            environmentServiceName: 'PipelineConnection'
            providerAzureRmSubscriptionId: '$(subscription_id)'

      
  - stage: Release
    dependsOn: Test
    jobs:
    - job: Create_Github_Release
      steps:
      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'Github'
          repositoryName: 'c45/bestrong-infra'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'gitTag'
          tagPattern: 'v1.*'
          releaseNotesSource: 'inline'
          changeLogCompareToRelease: 'lastFullRelease'
          changeLogType: 'commitBased'
      