trigger: 
  branches:
    include:
      - master
  paths:
    include:
      - dev/*
    exclude:
      - README.md

pool: 
    vmImage: ubuntu-latest

stages:
  - stage: Install_Terraform
    jobs:
    - job: Install_Terraform
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '1.5.2'

  - stage: Checkout_Repository
    dependsOn: Install_Terraform
    jobs:
    - job: Checkout_Repository
      steps:
      - checkout: self

  - stage: Terraform_Init
    dependsOn: Checkout_Repository
    jobs:
    - job: Terraform_Init
      steps:    
      - task: TerraformCLI@0
        inputs:
          command: 'init'
          workingDirectory: '$(workdir)'
          backendType: 'azurerm'
          backendServiceArm: 'PipelineConnection'
          backendAzureRmSubscriptionId: $(subscription_id)

  - stage: Terraform_Validate
    dependsOn: Terraform_Init
    jobs:
    - job: Terraform_Validate
      steps:    
      - task: TerraformCLI@0
        inputs:
          command: 'validate'
          workingDirectory: '$(workdir)'

  - stage: Terraform_Plan
    dependsOn: Terraform_Validate
    jobs:
    - job: Terraform_Plan
      steps:    
      - task: TerraformCLI@0
        inputs:
          command: 'plan'
          workingDirectory: '$(workdir)'
          environmentServiceName: 'PipelineConnection'
          providerAzureRmSubscriptionId: $(subscription_id)
          publishPlanResults: 'tfplan'
      
  - stage: Create_Release
    dependsOn: Terraform_Plan
    jobs:
    - job: Create_Github_Release
      steps:
      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'Github'
          repositoryName: 'c45/bestrong-infra'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'gitTag'
          tagPattern: 'v1.*'
          releaseNotesSource: 'inline'
          changeLogCompareToRelease: 'lastFullRelease'
          changeLogType: 'commitBased'
      