trigger: none
pr: none


pool: 
    vmImage: ubuntu-latest

stages:
  - stage: Prod
    jobs:
      - job: CI
        steps:
        - task: TerraformInstaller@0
          displayName: Install Terraform
          inputs:
            terraformVersion: 'v1.5.2'

        - checkout: self
          displayName: Checkout Repository  

        - task: TerraformCLI@0
          displayName: Terraform Init
          inputs:
            command: 'init'
            workingDirectory: '$(TF_ROOT)'
            backendType: 'azurerm'
            backendServiceArm: 'PipelineConnection'
            backendAzureRmSubscriptionId: $(SUBSCRIPTION_ID)

        - task: TerraformCLI@0
          displayName: Terraform Validate
          inputs:
            command: 'validate'
            workingDirectory: '$(TF_ROOT)'

        - task: TerraformCLI@0
          displayName: Terraform Plan
          inputs:
            command: 'plan'
            workingDirectory: '$(TF_ROOT)'
            environmentServiceName: 'PipelineConnection'
            providerAzureRmSubscriptionId: $(SUBSCRIPTION_ID)
            publishPlanResults: 'tfplan'

        - task: TerraformCLI@0
          displayName: Terraform Apply
          inputs:
            command: 'apply'
            workingDirectory: '$(TF_ROOT)'
            environmentServiceName: 'PipelineConnection'
            providerAzureRmSubscriptionId: '$(SUBSCRIPTION_ID)'

        - task: TerraformCLI@0
          inputs:
            command: 'destroy'
            workingDirectory: '$(TF_ROOT)'
            environmentServiceName: 'PipelineConnection'
            providerAzureRmSubscriptionId: '$(SUBSCRIPTION_ID)'
    