pr:
  branches:
    include:
      - master
  paths:
    include:
      - prod/*   

pool: 
    vmImage: ubuntu-latest

stages:
  - stage: PR
    jobs:
      - job: CI
        steps:
        - task: TerraformInstaller@0
          displayName: Install Terraform
          inputs:
            terraformVersion: 'v1.5.2'

        - checkout: self
          displayName: Checkout Repository  

        - task: TerraformCLI@0
          displayName: Terraform Init
          inputs:
            command: 'init'
            workingDirectory: '$(workdir)'
            backendType: 'azurerm'
            backendServiceArm: 'PipelineConnection'
            backendAzureRmSubscriptionId: $(subscription_id)

        - task: TerraformCLI@0
          displayName: Terraform Validate
          inputs:
            command: 'validate'
            workingDirectory: '$(workdir)'

        - task: TerraformCLI@0
          displayName: Terraform Plan
          inputs:
            command: 'plan'
            workingDirectory: '$(workdir)'
            environmentServiceName: 'PipelineConnection'
            providerAzureRmSubscriptionId: $(subscription_id)
            publishPlanResults: 'tfplan'
